### ISSUE TITLE
Is it possible to attach a tag to an armor stand?

### ISSUE THREAD

**Issue by pedrokarim** [keehl254/TagAPI#6]
I looked a little on spigot and github I didn't find a link to a discord so I ask the question here is it possible to attach a Tag to an armor stand?

![](https://img.ascencia.re/shKZnVIj.png)
_Here `entity` is a bukkit entity of armor stand_

it doesn't work no text appears above the armor stand!

**Comment by keehl254** [comment]
What version of Minecraft are you on? Is the ArmorStand being created in code, and if so, is it being spawned into the world before the tag is given? TagAPI decides to show a tag to a player when the Spawn Packet for the entity is sent to the viewing player. Would you have any plugins that interrupt this?
![Screenshot_7](https://user-images.githubusercontent.com/6056735/178812403-864dbad0-ac69-45cf-9ab0-db1ad9f6042c.png)
The code does work when paired with an entity I just generated using World#spawnEntity, so this is strange.
This probably isn't it... But TagAPI tracks entities using their entityID. Some entities will despawn when out of player scope and then 'respawn' when players are nearby (sometimes with a different entityID). I have a listener setup for clearing despawned entities from the system, but that means that the tag would have to be re-given. I will see about looking into this issue, but I don't think it's the problem.

I have to be at work soon, but my Discord is Keehl#2022

**Comment by AliasPedroKarim** [comment]
I think I found my problem ^^' and I think it's my fault. In my first post I didn't specify that the armor stand is invisible when I removed the invisibility setting everything worked fine ^^

Armor Stand visible :
![](https://img.ascencia.re/zjbqWDgF.png)

Armor Stand invisible :
![](https://img.ascencia.re/KOiyoNJi.png)

So I will close this issue because it was not a problem on your part, thanks for your help 😊 !
